# Generated by Django 5.2.2 on 2025-06-09 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='游戏ID')),
                ('rows', models.PositiveIntegerField(default=9, verbose_name='行数')),
                ('cols', models.PositiveIntegerField(default=9, verbose_name='列数')),
                ('mines', models.PositiveIntegerField(default=10, verbose_name='雷数')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完成情况')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='日期')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏列表',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MineMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=256)),
                ('mines', models.CharField(max_length=256)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrix', to='game.game')),
            ],
        ),
    ]
