# Generated by Django 5.2.2 on 2025-06-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='minematrix',
            name='mines',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='minematrix',
            name='state',
            field=models.CharField(max_length=999),
        ),
    ]
