# Generated by Django 5.2.2 on 2025-06-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_end_time_game_start_time_alter_minematrix_mines_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date'], 'verbose_name': '游戏', 'verbose_name_plural': '游戏列表'},
        ),
        migrations.AddField(
            model_name='game',
            name='game_state',
            field=models.JSONField(default=dict, verbose_name='游戏状态'),
        ),
        migrations.DeleteModel(
            name='MineMatrix',
        ),
    ]
