# Generated by Django 5.2.2 on 2025-06-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_options_game_game_state_delete_minematrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='是否成功'),
        ),
    ]
