# Generated by Django 5.2.2 on 2025-06-09 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_is_success'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allow_spectators',
            field=models.BooleanField(default=True, verbose_name='允许观众'),
        ),
        migrations.AddField(
            model_name='game',
            name='spectator_count',
            field=models.PositiveIntegerField(default=0, verbose_name='观众数量'),
        ),
        migrations.CreateModel(
            name='SpectatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='游戏')),
                ('spectator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='观众')),
            ],
            options={
                'verbose_name': '观众会话',
                'verbose_name_plural': '观众会话列表',
                'unique_together': {('game', 'spectator')},
            },
        ),
    ]
